# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Say
version:      0.06
version_from: lib/Perl6/Say.pm
installdirs:  site
requires:
    Carp:                          0
    IO::Handle:                    0
    Scalar::Util:                  1.07
    Test::More:                    0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
