--- #YAML:1.0
name:                Perl6-Say
version:             0.08
abstract:            'print' -- but no newline needed
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          0
    IO::Handle:                    0
    Scalar::Util:                  1.07
    Test::More:                    0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - James E Keenan (jkeenan@cpan.org)
