--- #YAML:1.0
name:               Perl6-Say
version:            0.15
abstract:           'print' -- but no newline needed
author:
    - James E Keenan (jkeenan@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    IO::Handle:    0
    Scalar::Util:  1.07
    Test::More:    0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
